#!/bin/bash
regex="pr/([0-9]+)"
if [[ $1 =~ $regex ]]
then
    git fetch origin pull/${BASH_REMATCH[1]}/head:pr/${BASH_REMATCH[1]}
    git checkout pr/${BASH_REMATCH[1]}
else
    echo 'invalid pr.  Please use format git cpr pr/123'
fi
