#!/bin/bash
regex="pr/([0-9]+)"
if [[ $1 =~ $regex ]]
then
    git fetch origin pull/${BASH_REMATCH[1]}/head:pr/${BASH_REMATCH[1]}
    git checkout pr/${BASH_REMATCH[1]}
else
    url=$1
    ID=$(echo $url | tr '/' ' ' | awk '{print $6}')
    BRANCHNAME=$(curl $url | grep head-ref | tr ':' '\n' | awk '0 == NR % 3' | tr '>' ' ' | tr '<' ' ' | awk '{print $3}')
    git fetch origin pull/$ID/head:$BRANCHNAME
    git checkout $BRANCHNAME
fi
